[tool.pytest.ini_options]
# for "normal" test output
addopts = "--tb native -v -r fxX --maxfail=300 -p no:warnings"
# for verbose test output (like engine.echo = True)
#addopts = "--tb native -v -r fxX --maxfail=300 -p no:warnings --log-info=sqlalchemy.engine"
python_files = "test/*test_*.py"

# SQLAlchemy-Firebird configuration for Black.

[tool.black]
line-length = 79
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.github
  | \.pytest_cache
  | _venv
)/
'''
